//
//  MockExercisesListView.swift
//  FitnessWikiTests
//
//  Created by AbdooMaaz's playground on 28.06.22.
//  Generated by: Swift Mock Generator for Xcode

@testable import FitnessWiki
import Foundation
import UIKit

final class MockExercisesListView: ExercisesListViewInterface {

    var invokedPrepareTableView = false
    var invokedPrepareTableViewCount = 0

    func prepareTableView() {
        invokedPrepareTableView = true
        invokedPrepareTableViewCount += 1
    }

    var invokedReloadTableView = false
    var invokedReloadTableViewCount = 0

    func reloadTableView() {
        invokedReloadTableView = true
        invokedReloadTableViewCount += 1
    }

    var invokedShowAlert = false
    var invokedShowAlertCount = 0
    var invokedShowAlertParameters: (alert: UIAlertController, animated: Bool)?
    var invokedShowAlertParametersList = [(alert: UIAlertController, animated: Bool)]()

    func showAlert(_ alert: UIAlertController, animated: Bool ) {
        invokedShowAlert = true
        invokedShowAlertCount += 1
        invokedShowAlertParameters = (alert, animated)
        invokedShowAlertParametersList.append((alert, animated))
    }
}
